---
apiVersion: v1
kind: Namespace
metadata:
  name: es
  labels:
    name: es
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
  labels:
    name: istio-system
    istio-injection: enabled
