
# Copyright (C) 2020-2023 Cognizant Digital Business, Evolutionary AI.
# All Rights Reserved.
#
# This software is a trade secret, and contains proprietary and confidential
# materials of Cognizant Digital Business Evolutionary AI.
# Cognizant Digital Business prohibits the use, transmission, copying,
# distribution, or modification of this software outside of the
# Cognizant Digital Business EAI organization.
#
# END COPYRIGHT

class Trainer():
    '''
    A Trainer is an abstract interface for training algorithms that can work
    on a population. A population is a collection of trainable material.

    A single training pass starts with a population, which can be empty but
    not None, and given some (potentially streamed) Source of data sample
    Records, the algorithm makes some progress towards solving a problem by
    returning a more refined population.

    This is intended to be a Pure Function. This means that inputs are
    expected to be immutable.

    Depending on the implementation, this might return new versions of the
    existing TrainableType passed in, or it could mean a complete new
    population that was generated by the implementation (as in evolution).
    '''

    def train(self, initial_population, data):
        '''
        Trains a population of objects using some data.

        :param initial_population:
                a potentially empty immutable collection of material to be
                trained. If the collection if empty, a new population can be
                created. The collection can also be used to pick up from where
                a previous training left off. Collections of size one are
                perfectly acceptable, depending on the algorithm.

        :param data:
                a potentially streamed Source of data sample Records against
                which the models should be evaluated.  This can be None
                if it is understood within the domain the trainer is applied
                to that data is either generated or fetched internally
                to the train() process.

        :return: a more refined population
        '''
        raise NotImplementedError
