# Contains the Docker image versions for the V2 service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: esp-blue
spec:
  replicas: 2
  template:
    spec:
      containers:
          - name: esp
            image: 634208487213.dkr.ecr.us-west-2.amazonaws.com/esp:2.7.1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: esp-green
spec:
  replicas: 2
  template:
    spec:
      containers:
          - name: esp
            image: 634208487213.dkr.ecr.us-west-2.amazonaws.com/esp:2.7.1
---
