---
apiVersion: authentication.istio.io/v1alpha1
kind: Policy
metadata:
  name: esp-auth-policy
spec:
  targets:
  - name: esp
  peers:
  - mtls: {}
  origins:
  - jwt:
      issuer: "https://cognizant-ai.auth0.com/"
      jwksUri: "https://cognizant-ai.auth0.com/.well-known/jwks.json"
      audiences:
        - "http://api.cognizant-ai.dev/esp"
      triggerRules:
      - excluded_paths:
          - prefix: "/grpc.reflection.v1alpha.ServerReflection/"
  principalBinding: USE_ORIGIN
---
apiVersion: config.istio.io/v1alpha2
kind: rule
metadata:
  name: esp-add-auth-headers
  namespace: istio-system
spec:
  match: source.labels["istio"] == "ingressgateway"
  actions:
  - handler: keyval.istio-system
    instances: [ keyval ]
  request_header_operations:
  - name: X-company-userId
    values:
    - request.auth.claims["sub"]
